# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/soilspecdata',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/soilspecdata',
                'lib_path': 'soilspecdata'},
  'syms': {'soilspecdata.core': {'soilspecdata.core.foo': ('core.html#foo', 'soilspecdata/core.py')}}}
