"""Main types used in the package.

Docs: https://franckalbinet.github.io/soilspecdata/types.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_types.ipynb.

# %% auto #0
__all__ = ['SpectraData', 'Spectra']

# %% ../nbs/00_types.ipynb #165defde
from dataclasses import dataclass, field, fields
import numpy as np

# %% ../nbs/00_types.ipynb #1d3a0275
@dataclass
class Spectra:
    "Spectra of several samples, measured at the same wavenumbers"
    wavenumbers:np.ndarray # Wavenumbers in cm⁻¹, in increasing order
    spectra:np.ndarray # One row per sample, one column per wavenumber
    measurement_type:str # `abs` (absorbance) or `ref` (reflectance)
    sample_ids:np.ndarray # Sample ID of each row of `spectra`
    source:object=field(default=None, repr=False, compare=False) # Object the spectra came from, such as an `OSSL`

    def __str__(self):
        'Pretty print the Spectra object'
        sections = [
            ("Spectra attributes", f"Available attributes: {', '.join(f.name for f in fields(self) if f.repr)}"),
            
            ("Wavenumbers", 
                f"{np.array2string(self.wavenumbers[:10], precision=2, separator=', ')}\n"
                f"Shape: {self.wavenumbers.shape}"),
            
            ("Spectra", 
                f"{np.array2string(self.spectra[:5,:5], precision=4, separator=', ')}\n"
                f"Shape: {self.spectra.shape}"),
            
            ("Measurement type (Reflectance or Absorbance)", self.measurement_type),
            
            ("Sample IDs", 
                f"{np.array2string(self.sample_ids[:10], separator=', ')}\n"
                f"Total samples: {len(self.sample_ids)}")]
        
        return '\n\n'.join(f"{title}:\n{'-'*len(title)}\n{content}" 
            for title, content in sections)

# %% ../nbs/00_types.ipynb #3f1ee11b
SpectraData = Spectra
